#define Usage			1
#define BadOpt			2
#define NoOp			3
#define NoMakefile		4
#define CantMake		5
#define	TopTooLong		6
#define	CantOpenBldref	7
#define	SetupIndex		8
#define	RefIndex		9
#define	NoRefStruct		10
#define	NoRefNode		11
#define	NoDupPath		12
#define BtInsert		13
#define	BtDup			14
#define	DupPath			15
#define	ArgTooLong		16
#define	RefTooLong		17
#define	CommandLine		18
#define CantUnlink		19
#define CantStat		20
#define	CantLink		21
#define	CantOpen		22
#define	CantWrite		23
#define	CantRename		24
