#define Usage			1
#define NoBldref		2
#define NoClass			3
#define BadOpt			4
#define BadBldref		5
#define NoSetup			6
#define NoBldRefList		7
#define BadBldRefList		8
#define SearchTooLong		9
#define BadSearch		10
#define PathTooLong		11
#define BadPath			12
#define NoMem			13
#define BadFilePath		14
#define BadFile			15
#define NoFile			16
#define Path1TooLong		17
#define LandA			18
#define LandP			19
#define LandS			20
#define LandCapS		21
#define LandClass		22
